name: Integration Continue et deploiement Continue(CI/CD)

on:

    push:
        branches: -cicd
    pull_request:
        branches: -cicd

jobs: 
    frontend-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: /
        steps:
            - uses: actions/checkout@v3

            - name: Installation des dépendances
              run: npm install

            - name: Effectuer test
              run: npm test
    integration-test:
        runs-on: ubuntu-latest
        needs: [frontend-test]
        steps: 
            - uses: actions/checkout@v3

    build-image:
        runs-on: ubuntu-test
        needs: [integration-test]
        if: ${{ github.event_name == 'push' && github.ref_name == 'main'}}

        strategy:
            matrix:
                component: [frontend-test]
        permissions:
            packages: write
            contents: read
        
        steps:
            - uses: actions/checkout@v3

            - name: Se connecter
              run: echo"${{secrets.GITHUB_TOKEN}}"

            - name: Construire l'image docker
              uses: build/build-push-action@v2
              with:
                context: ${{matrix.component}}
                file: ${{matrix.component}}/Dockerfile
                push: true
                tags: ghcr.io/${{github.repository_owner}}/spm-${{matrix.component}}:${{github.ref_name}}


    