
name: Mon porfolio CI
on:
  push:
    branches:
      - test_ci_cd
  pull_request:
    branches:
      - test_ci_cd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
     
    - name: Run Yarn 
      run: yarn
    - name: Run tests
      run: yarn test
